#28 Organizing pages with require_once. Worked only with index.php
ReginaBorisova/portfolio pull request #62
Opened 2023-05-16 19:57 UTC by ReginaBorisova

#28 Organizing pages with require_once. Worked only with index.php. Changes made: 
    - created directory template/content/;
    - created a file template/page.phtml with basic structure of the page which contains common parts of all pages;
    - in the index.php file created a variable $content and used the require_once function 
        <?php
    $content = 'home';
    require_once __DIR__ . '/template/page.phtml';
    ?>
    - Tested index.php. Everything works properly.
    
Kindly request to observe the work done to index.php to make sure that the task is understood by me the right way. Need your permission to work the same way with work.php, about.php contact.php.

2023-05-16 20:21 UTC, sashas777 requested changes

2023-05-16 20:21 UTC, sashas777 commented on template/page.phtml
> +    <?php require_once __DIR__ . '/../template/content/home.phtml'; ?>
@ReginaBorisova 
You may need to use variable to load the template dynamically.  Example:
```
 <?php
  $content = 'about'; 
  require_once __DIR__ . '/../template/content/'.$content.'.phtml'; 
?>
```

2023-05-17 03:49 UTC, ReginaBorisova commented
#28 Organizing pages with require_once. Worked with about.php, contact.php, work.php. Changes done:

    - in the directory template/content/  created mywork.phtml, about.phtml, contact.phtml where respectively placed mail unique parts of the parent pages;
    - changes variable to $content to load the template dynamically, and used the require_once function in the about.php, work.php, contact.php;
    
Kindly request to review the completed task and provide future guidance if needed

2023-05-17 05:03 UTC, sashas777 approved these changes

2023-05-17 05:03 UTC, merged