Feature/68
ReginaBorisova/portfolio pull request #74
Opened 2023-05-26 16:38 UTC by ReginaBorisova

#68 Function for the menu page:
    - created function which determines the current page and adds "id='here'";
    - modified code on the menu.phtml which calls the above mentioned function;
    
Request to approve

2023-05-27 03:00 UTC, sashas777 requested changes
@ReginaBorisova 
The file config/variables_work.php is not related to this task

2023-05-30 15:47 UTC, ReginaBorisova commented
Resolve # 68  Function for the menu page. 
    - pulled origin master, committed without config/variables_work.php which is not related to this task.
    
Kindly request to approve

2023-05-31 02:11 UTC, sashas777 requested changes

2023-05-31 02:11 UTC, sashas777 commented on config/variables_work.php
>  $projects = [
@ReginaBorisova 
This file doesnt seem to be part of this task.

2023-06-02 02:41 UTC, sashas777 approved these changes

2023-06-02 04:10 UTC, sashas777 approved these changes

2023-06-02 04:10 UTC, merged